#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Mysterious/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Mysterious/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Mysterious/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
print(arr := np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [12]:
print(arr.nbytes)
print(arr.size * arr.itemsize)

80
80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
python
import numpy
numpy.info(numpy.add)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [17]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [21]:
print(arr := np.arange(10, 50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [24]:
print(np.flip(arr))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [30]:
print(arr := np.arange(0, 9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [35]:
arr = [1,2,0,0,4,0]
print(np.nonzero(arr))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [45]:
print(arr := np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [48]:
print(arr := np.random.random((3,3,3)))

[[[0.152314   0.05114576 0.33774556]
  [0.95221436 0.39633924 0.55926738]
  [0.80674796 0.68084205 0.73576992]]

 [[0.87206315 0.63885509 0.04264243]
  [0.75587354 0.46513512 0.88901217]
  [0.08027178 0.60815567 0.59512104]]

 [[0.55631227 0.96711747 0.09308639]
  [0.15953673 0.61746238 0.43690719]
  [0.17454227 0.4209724  0.44006633]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [54]:
arr = np.random.random((10,10))
print(arr.min(), arr.max())

0.01362303514423091 0.9758600345387252


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [58]:
print(arr := np.random.random(30).mean())

0.5026866145733231
0.5026866145733231


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [82]:
arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [95]:
arr = np.ones((5,5))
arr = np.pad(arr, 1, constant_values=0)
print(arr)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [103]:
print(0 * np.nan,
      np.nan == np.nan,
      np.inf > np.nan,
      np.nan - np.nan,
      np.nan in set([np.nan]),
      0.3 == 3 * 0.1, sep='\n')

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [111]:
print(arr := np.diag(np.arange(1, 5), k=-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [168]:
pattern = np.array([[0,1],[1,0]])
print(arr := np.tile(pattern, (4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [181]:
print(ind := np.unravel_index(99, (6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [182]:
pattern = np.array([[0,1],[1,0]])
print(arr := np.tile(pattern, (4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [188]:
arr = np.random.random((5,5))
print(arr)
arr = (arr - np.mean(arr)) / np.std(arr)
print(arr)

[[0.8426264  0.74087174 0.55428857 0.88099707 0.15759046]
 [0.50393552 0.88106013 0.64947499 0.13873337 0.91433166]
 [0.14086566 0.98525402 0.43644783 0.78222792 0.05711805]
 [0.52592393 0.80471642 0.85578191 0.75516228 0.49156069]
 [0.51770748 0.92766143 0.18362024 0.22394718 0.22486155]]
[[ 0.93684635  0.59089645 -0.04345709  1.06730063 -1.39216854]
 [-0.21464958  1.06751504  0.28016182 -1.45627971  1.180633  ]
 [-1.44903027  1.42175792 -0.44409717  0.731501   -1.73375901]
 [-0.13989245  0.80795837  0.98157303  0.63948206 -0.25672209]
 [-0.16782707  1.22595215 -1.30367137 -1.16656611 -1.16345738]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [200]:
arr = np.dtype([('r', np.ubyte),
               ('g', np.ubyte),
               ('b', np.ubyte),
               ('a', np.ubyte),])
print(arr)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [202]:
arr1 = np.random.random((5,3))
arr2 = np.random.random((3,2))
print(arr := arr1 @ arr2)

[[1.40502802 0.92840711]
 [1.23591979 1.06090442]
 [1.05515676 0.78007338]
 [1.24685574 1.00880313]
 [0.72400504 0.55333317]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [210]:
arr = np.arange(20)
for i in range(4, 8):
    arr[i] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14 15 16 17 18 19]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [212]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [230]:
arr = np.arange(5)
print(arr**arr,
      2 << arr >> 2,
      arr <- arr,
      1j*arr,
      arr/1/1,
      # (arr < arr > arr) -> illegal
      sep='\n')

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [236]:
print(np.array(0) / np.array(0),
      np.array(0) // np.array(0),
      np.array([np.nan]).astype(int).astype(float),
     sep='\n')

nan
0
[-2.14748365e+09]


<ipython-input-236-43779f57d63d>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0),
<ipython-input-236-43779f57d63d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0),


#### 29. How to round away from zero a float array ? (★☆☆)

In [251]:
arr = np.random.randn(10)
print(arr)
print(np.where(arr > 0, np.ceil(arr), np.floor(arr)))

[ 1.96250662  2.75305323 -0.7686708   0.70853365 -1.52878323  1.39596565
  0.33584996 -0.01043623  0.64183974 -0.18558892]
[ 2.  3. -1.  1. -2.  2.  1. -1.  1. -1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [253]:
print(arr1 := np.random.randint(0, 10, 10))
print(arr2 := np.random.randint(0, 10, 10))
print(np.intersect1d(arr1, arr2))

[7 3 8 6 5 0 0 1 2 9]
[4 9 0 8 5 5 4 4 3 9]
[0 3 5 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
ign = np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [489]:
print(np.sqrt(-1) == np.emath.sqrt(-1)) # False

False


<ipython-input-489-947ae08d9cba>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1)) # False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [260]:
print(today := np.datetime64('today'))
print(yesterday := today - np.timedelta64(1))
print(tomorrow := today + np.timedelta64(1))

2021-01-31
2021-01-30
2021-02-01


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [265]:
print(arr := np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [309]:
A = np.ones(5)
B = np.ones(5)

np.add(A,B,out=B)
np.divide(A, 2, out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1., -1., -1., -1., -1.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [320]:
arr = np.random.uniform(0,10,10)
print(arr)
print(arr // 1)
print(np.floor(arr))
print(np.trunc(arr))
print(arr.astype(int))
print(arr - arr%1)

[4.64945334 8.57523446 8.61685998 5.12242636 5.73312595 2.61003091
 8.08053821 5.28748677 7.97700553 2.2533499 ]
[4. 8. 8. 5. 5. 2. 8. 5. 7. 2.]
[4. 8. 8. 5. 5. 2. 8. 5. 7. 2.]
[4. 8. 8. 5. 5. 2. 8. 5. 7. 2.]
[4 8 8 5 5 2 8 5 7 2]
[4. 8. 8. 5. 5. 2. 8. 5. 7. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [329]:
pattern = np.arange(5)
arr = np.tile(pattern, (5,1))
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [333]:
gen = [i for i in range(10)]
arr = np.fromiter(gen, float)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [337]:
print(arr := np.linspace(0, 1, 11)[1:-1])

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [345]:
arr = np.random.uniform(0, 100, 10)
print(np.sort(arr))

[ 2.03258868 14.47842256 18.69382233 38.8505093  50.36749523 62.2270558
 65.89111324 76.78351444 77.22009246 85.31813231]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [346]:
arr = np.random.uniform(0, 100, 10)
print(np.add.reduce(arr))

423.55583021941175
423.55583021941175


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [352]:
A = np.random.randint(0, 10, 5)
B = np.random.randint(0, 10, 5)
print(np.array_equal(A, B))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [363]:
arr = np.random.uniform(0, 100, 10)
arr.flags.writeable = False
arr[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [396]:
cart = np.random.randint(0, 10, 20).reshape(10, 2)
print(cart, '\n')

X, Y = cart[:,0], cart[:,1]
rho = np.sqrt(X**2 + Y**2)
phi = np.arctan2(Y, X)

polar = np.column_stack((rho, phi))
print(polar)

[[9 4]
 [8 5]
 [5 5]
 [2 0]
 [8 2]
 [2 2]
 [2 6]
 [2 5]
 [7 4]
 [0 5]] 

[[9.8488578  0.41822433]
 [9.43398113 0.55859932]
 [7.07106781 0.78539816]
 [2.         0.        ]
 [8.24621125 0.24497866]
 [2.82842712 0.78539816]
 [6.32455532 1.24904577]
 [5.38516481 1.19028995]
 [8.06225775 0.51914611]
 [5.         1.57079633]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [429]:
arr = np.random.randint(0, 100, 10)
print(arr)
arr[arr.argmax()] = 0
print(arr)

[14 36 24 71 77 70 77 68 27 49]
[14 36 24 71  0 70 77 68 27 49]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [432]:
arr = np.zeros((5,5), [('x',float), ('y',float)])
print(arr)
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(arr)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [464]:
X = np.array([1,2,3,4])
Y = np.array([5,6,7])
cm = 1.0/np.subtract.outer(X,Y)

print(cm)

[[-0.25       -0.2        -0.16666667]
 [-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [488]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [486]:
np.set_printoptions(threshold=float("inf"))
arr = np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [487]:
arr = np.arange(100)
scal = np.random.uniform(0,100)
print(scal)
index = (np.abs(arr-scal)).argmin()
print(arr[index])

74.06881688910723
74
